name: "Tests"

on:
  pull_request:
  push:
    branches:
      - main

defaults:
 run:
   shell: bash

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # Use MSYS2's bash.exe in subsequent steps.
      - if: startsWith(matrix.os, 'windows-')
        run: echo 'C:\msys64\usr\bin' >> $GITHUB_PATH
      - run: go mod download
      - run: make fmt
      - run: make tidy
      - run: make vet
      - run: make test-generate
      - run: make test-unit
      - run: make test-system
      - run: make test-heavy
        env:
          MSYS2_ARG_CONV_EXCL: '*'
  output-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - uses: actions/checkout@v2
      - run: make install
      - run: make output-check
